// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgnYLgwEFRS5tecreeheIXBGd7vNmeHY4',
    appId: '1:221716491824:web:ec825dee2537ba820087f5',
    messagingSenderId: '221716491824',
    projectId: 'nkust-schedule-app',
    authDomain: 'nkust-schedule-app.firebaseapp.com',
    storageBucket: 'nkust-schedule-app.firebasestorage.app',
    measurementId: 'G-DL57XPMPW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ZDmmxgVuxgykcg-nwdDgF8jedOB0SiY',
    appId: '1:221716491824:android:594ab02d6f6b8a080087f5',
    messagingSenderId: '221716491824',
    projectId: 'nkust-schedule-app',
    storageBucket: 'nkust-schedule-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSQ8OzTrsFtmeOqT2O_oJxCdp1hfaTYU',
    appId: '1:221716491824:ios:192fc52c5b2b49940087f5',
    messagingSenderId: '221716491824',
    projectId: 'nkust-schedule-app',
    storageBucket: 'nkust-schedule-app.firebasestorage.app',
    iosBundleId: 'com.example.classScheduleManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSQ8OzTrsFtmeOqT2O_oJxCdp1hfaTYU',
    appId: '1:221716491824:ios:192fc52c5b2b49940087f5',
    messagingSenderId: '221716491824',
    projectId: 'nkust-schedule-app',
    storageBucket: 'nkust-schedule-app.firebasestorage.app',
    iosBundleId: 'com.example.classScheduleManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgnYLgwEFRS5tecreeheIXBGd7vNmeHY4',
    appId: '1:221716491824:web:22332ec495cef2600087f5',
    messagingSenderId: '221716491824',
    projectId: 'nkust-schedule-app',
    authDomain: 'nkust-schedule-app.firebaseapp.com',
    storageBucket: 'nkust-schedule-app.firebasestorage.app',
    measurementId: 'G-6K6YDJ801C',
  );
}
